#
# Makefile for misc devices that really don't fit anywhere else.
#

ifdef MTK_LEGCY
include $(srctree)/drivers/misc/mediatek/Makefile.custom
endif

ccflags-y += -Wno-unused-variable -g
ccflags-y += -Wno-unused-function -g
obj-y += ili9806e_hlt_hd720_dsi.o




