#
# Makefile for misc devices that really don't fit anywhere else.
#
ifdef MTK_LEGCY
include $(srctree)/drivers/misc/mediatek/Makefile.custom
endif

ccflags-y += -Wno-unused-variable -g
ccflags-y += -Wno-unused-function -g

obj-y +=ili9881_hsd_hd720_5p0_hl_t592_otd.o




