#ifndef _CUST_PE_H_
#define _CUST_PE_H_

/* Pump Express support (fast charging) */
#ifdef CONFIG_MTK_PUMP_EXPRESS_PLUS_SUPPORT
#define TA_START_BATTERY_SOC	1
#define TA_STOP_BATTERY_SOC 	95
#if defined(CONFIG_NCP1854_DUAL_SUPPORT)
#define TA_AC_9V_INPUT_CURRENT	CHARGE_CURRENT_3000_00_MA
#define TA_AC_7V_INPUT_CURRENT	CHARGE_CURRENT_3000_00_MA
#define TA_AC_CHARGING_CURRENT	CHARGE_CURRENT_3000_00_MA
#else
#define TA_AC_9V_INPUT_CURRENT	CHARGE_CURRENT_2000_00_MA
#define TA_AC_7V_INPUT_CURRENT	CHARGE_CURRENT_2200_00_MA
#define TA_AC_CHARGING_CURRENT	CHARGE_CURRENT_2575_00_MA
#endif
#define TA_9V_SUPPORT

#ifdef CONFIG_NCP1854_DUAL_SUPPORT
//#define TA_12V_SUPPORT
#endif

#undef V_CHARGER_MAX

#ifdef TA_12V_SUPPORT
#define V_CHARGER_MAX 12500				// 10.5 V

#else
#ifdef TA_9V_SUPPORT
#define V_CHARGER_MAX 10500				// 10.5 V
#else
#define V_CHARGER_MAX 7500				// 7.5 V
#endif
#endif
#endif

#endif /* _CUST_PE_H_ */ 
