subdir-ccflags-y += -Werror -I$(srctree)/drivers/misc/mediatek/include \
-I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include \
-I$(srctree)/drivers/misc/mediatek/include/mt-plat

obj-$(CONFIG_MTK_SPI) += spi.o spi-dev.o
